"""add message edit fields

Revision ID: e6106b621222
Revises: 053ab5aa5d73
Create Date: 2025-07-20 15:00:08.547311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6106b621222'
down_revision = '053ab5aa5d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('edit_count')
        batch_op.drop_column('edited')

    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('edit_count')
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
